rest:
  client:
    default:
      timeout: 10002
service:
  uri:
    pokemon: https://pokeapi.co/api/v2/pokemon/
    digimon: https://digimon-api.vercel.app/api/digimon/name/
dataBase:
  kafkaUrl: localhost
  kafkaPort: 29092